### ISSUE TITLE
What is the definition of Box.heading?

### ISSUE THREAD

**Issue by kd0aij** [PyFlightCoach/FlightAnalysis#5]
https://github.com/PyFlightCoach/FlightAnalysis/blob/c709e92c19acb2eaba94fe935c03399c06e45e87/flightanalysis/flightline.py#L112
and
https://github.com/PyFlightCoach/FlightAnalysis/blob/main/flightanalysis/flightline.py#L84

Is the Box heading specified in radians CCW from the X axis (as returned by atan2(y,x)), or is it a compass heading which is specified in degrees CW from North?
Also, is the X axis the world frame X axis, and does that axis point North, or East?

**Comment by ThomasDavid0** [comment]
Either works for me. My initial plan was to go for radians CW from north, when viewed from above. All that matters at this stage is that we can transform the flight data when it goes into a Section object so that the sequence is in a standard coordinate frame. It doesn't really matter what that system is, but the one we have (origin on pilot position, Y axis towards centre, Z up) seems sensible to me. 

The idea with FlightLine.from_initial() was that you boot the flight controller with the plane sitting on the pilot position pointing towards centre. I thought it would be a convenient way to define the box when you haven't got one setup for a particular flying site, but on the whole it doesn't work too well as the initial position in the log is not necessarily very accurate and it is difficult to position the plane. Likewise FlightLine.from_points() is just a convenience method, I'm not trying to define a standard with it!

**Comment by kd0aij** [comment]
Thanks for looking at this: the reason I'm asking these questions is that I'm having a lot of trouble porting my Octave code.  I don't get the same results and I believe the root of my problems is a difference in reference frames.
  
This is the "maneuver plane roll/pitch/yaw" that I get from Octave for the vertical 8 in your 0100.bin log:
https://github.com/kd0aij/octave_log_analysis/blob/master/examples/FlightCoach-example-log-100/fc100_4_eulerVmp.svg
That's looking very good to me, and the roll color coding shows that you are within a tolerance of 15 degrees for the entire maneuver except during the rolls:
https://github.com/kd0aij/octave_log_analysis/blob/master/examples/FlightCoach-example-log-100/fc100_4_3D.svg
I"ve added little wing/tail planes to the 3D plot to visually verify that the roll color agrees with the quaternion attitude.

Unfortunately, I've been unable to figure out the differences between my ENU world frame and your contest frame.  Apparently I'm easily confused by coord frame transformations :)  It's frustrating because the difference should only be in the definition of "heading" from which the normal to the maneuver plane can be defined.

I realize now that I'm using the term "heading" for euler yaw, and that the only place I use a compass heading is in specifying the runway direction. For my runway, the heading is 106 degrees and the rotation from world (ENU) to box is 106-90.  For your runway, I need a runway compass heading of -122 and the rotation to the box would be -212 degrees.

This rotation is done using Octave method lla2xyz, but I apply this rotation only for display.  All of the maneuverRPY calculations are done using the unaltered ardupilot POS and ATT data.

**Comment by kd0aij** [comment]
I think I've finally found the difference between the Octave implementation and yours: difference in the definition of euler angles.
I'm using what I call "xyz-fixed Euler angles", and your Quaternion to_euler method is returning something else; the order of rotations is different.
My convention is the same as the one used in ArduPilot: https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Math/quaternion.cpp
It looks like you used the xyz-fixed/ardupilot definition for quaternion.from_euler, but a different one for to_euler, and it took me a while to suspect that as a problem.
We should probably write tests to verify that all mathematical conventions match those used by ArduPilot to avoid such confusion in the future.

**Comment by kd0aij** [comment]
![image](https://user-images.githubusercontent.com/2300221/120205980-d8923a00-c1e7-11eb-9f22-3dd56ddb1cb3.png)

**Comment by ThomasDavid0** [comment]
This is looking very promising. Sorry that I haven't had a chance to look in the last few days, but I'll get onto it as soon as I can. I noticed that bug when I was trying to create json files for the flight coach plotter. There is a hack in the main PyFlightCoach module to do this now. Have you added some functionality to the plotting module to generate the ribbon, rather than just two lines? The coloured plots look great.

**Comment by kd0aij** [comment]
I generated a PR against the geometry module a few days ago to get Euler angles into xyz-fixed (ardupilot roll/pitch/yaw) form:
https://github.com/PyFlightCoach/geometry/pull/3

I added the ribbon along with the color-coding method in traces.py in branch maneuverRPY of my fork of FlightPlotting:
https://github.com/kd0aij/FlightPlotting/commits/maneuverRPY
I haven't generated a PR against FlightPlotting since you might want to move the new logic somewhere other than traces.py.

The script that generates the plots above is in the maneuverRPY branch of my fork of PyFlightCoach:
https://github.com/kd0aij/PyFlightCoach/tree/maneuverRPY -- examples/test_plot.py
You can turn the box edges, tiptraces, ribbon and icons on/off by clicking on the legend.

**Comment by ThomasDavid0** [comment]
Thanks for the geometry PR, I've merged that. I've also merged the ENU experiment one, but with the original box heading definition. I think a sketch of the definitions would have saved all the confusion, so I'll think about adding something to the readme. 

The plots in your maneuverRPY branch looks really nice, but I agree a lot of the functionality would be better moved into the relevant sub-modules (either geometry, flightanalysis or the main PyFlightCoach one). I will spend a bit of time today understanding your manoeuvre plane stuff to see how it fits.

**Comment by ThomasDavid0** [comment]
I'm in the process of reorganising the way manoeuvres and elements are labelled when they are constructed or broken up. At the moment I just tag a couple of columns onto the section data, but I'm working towards a better way, perhaps with sections that contain views of the data in a parent section, or something like that! I think the principal plane for an element, or perhaps manoeuvre,  will then be useful for calculating roll angle and radius errors. It is all very much wip in the moment though! 

I think the process will look like this:
1 parse sequence definition
2 construct labelled template flight data
3 read and rotate actual flight data
4 temporal alignment to label actual flight data
5 create new template, with various higher level parameters for each manoeuvre adjusted so that the template manoeuvres match the flown manoeuvres as closely as possible within the judging criteria. ( Line lengths, loop diameters, roll rates etc)
6 compare the new template to the flown data.

**Comment by kd0aij** [comment]
That sounds good to me. Is "principle plane" a better term for what I've been calling the "maneuver plane"?
